# 01_Numpy 기초

###  Numpy란?
* Array(배열) 구조로 고성능 다차원 배열 객체와 연산 등의 기능 제공

In [2]:
import numpy as np

In [5]:
a = np.array(1)
a

array(1)

### 배열 생성
* 한가지 자료형으로만 생성 가능

In [7]:
ndarr_1 = np.array([1,2,3])    # list와 달리 ',' 아닌 공백 구분자
print(ndarr_1)

[1 2 3]


In [8]:
ndarr_2 = np.array([1,2.0,3])   # float 형식
print(ndarr_2)

[1. 2. 3.]


In [9]:
ndarr_3 = np.array([1,2.0,'3'])   # 문자 형식
print(ndarr_3)

['1' '2.0' '3']


### 배열의 자료형 확인
* 자료형 확인 속성 : ndarray.dtype

In [10]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [12]:
print(np.array(1+2j).dtype)  # 허수 > complex 복소수
print(np.array(print).dtype)

complex128
object


* 자료형 지정

In [14]:
dtype1 = np.array([1,2,3], dtype = np.int8)   # 8byte int형
print(dtype1.dtype)  # 자료형 확인

int8


In [15]:
dtype2 = np.array([1,2,3], dtype = float)
print(dtype2.dtype)

float64


In [16]:
dtype3 = np.array([1,2,3], dtype = str)
print(dtype3.dtype)

<U1


* 주의해야 할 점

In [20]:
dtype4 = np.array([1,2.1,'3'], dtype = int)     # 형식을 바꿔줄 수 있는 형태의 경우 변경 가능
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [22]:
dtype5 = np.array([1,'data',print], dtype = float)    # 숫자문자가 아닌 문자열이 있는 경우 형태 변환 불가능(Error)
print(dtype5.dtype)

ValueError: could not convert string to float: 'data'

### 배열의 정보 확인
* 배열 크기 확인 : ndarray.shape

In [23]:
print(ndarr_1.shape)

(3,)


* 배열 차원 확인 : ndarray.ndim

In [24]:
print(ndarr_1.ndim)

1


### N차원 배열
- Scalar : 숫자
- Vector : 스칼라의 배열(1차원)
- Matrix : 벡터의 배열(2차원)
- Tensor : 매트릭스의 배열(3차원 이상)

### 1차원 배열

In [26]:
# 배열 생성
vector = np.array([1,2,3])
print(vector)
print(vector.shape)  # 크기
print(vector.ndim)   # 차원
print(vector.dtype)  # 자료형

[1 2 3]
(3,)
1
int32


### 2차원 배열

In [30]:
# 배열 생성
matrix = np.array([ [1,2,3],[4,5,6] ])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


### 3차원 배열

In [29]:
# 배열 생성
tensor = np.array([ [ [1,2,3],[4,5,6] ],[ [7,8,9],[10,11,12] ] ])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


* 배열 요소의 개수(크기) 확인 : ndarray.size

In [31]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


### 연습

In [36]:
a = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
2
9
(3, 3)


### 자료형 변환(리스트)

In [37]:
list1=[1,2,3]
arr1 = np.array(list1)
print(arr1)

[1 2 3]


In [38]:
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2, type(list2))

[1, 2, 3] <class 'list'>


* 2차원 리스트 변환(리스트에서 mdarray로)

In [40]:
list3=[ [1,2,3],[4,5,6]]
arr3 = np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


* shape이 다른 리스트인 경우

In [42]:
list4 = [[1,2,3,4],[5,6,7]]  # 자료 길이
arr4 = np.array(list4)
print(arr4)

[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\admin\AppData\Local\Temp\ipykernel_11364\310765174.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 =np.array(list4)


### 자료형 변환(튜플)

* ndarray > 튜플 변환

In [43]:
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

[1 2 3]


### 자료형 변환(세트, 딕셔너리)

* 집합, 세트

In [48]:
set1 = {1,2,3}
arr = np.array(set1)
print(arr, arr.size, arr.shape)

{1, 2, 3} 1 ()


* 딕셔너리

In [46]:
dict1 = {'a' :1, 'b' : 2, 'c' : 3}
arr = np.array(dict1)
print(arr, arr.size, arr.shape)

{'a': 1, 'b': 2, 'c': 3} 1 ()
