### 배열 인덱싱(리스트 유사)
* ndarray[col]
* ndarray[row][col]
* ndarray[rank][row][col]

In [8]:
list_ = [[[1,2],[3,4]], [[5,6],[7,8]]]
print(list_)
print(list_[0][0][0])   # 1 가져오기
print(list_[0][1][1])   # 4 가져오기
print(list_[1][1][0])   # 7 가져오기

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
1
4
7


In [9]:
import numpy as np 

arr_ = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr_)
print(arr_[0][0][0])   # 1 가져오기
print(arr_[0][1][1])   # 4 가져오기
print(arr_[1][1][0])   # 7 가져오기

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
4
7


### 배열 인덱싱(ndarray만 가능)
* array[row,col]
* array[rank,row,col]

In [11]:
arr_1 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr_1)
print(arr_1[0,0,0])   # 1 가져오기
print(arr_1[0,1,1])   # 4 가져오기
print(arr_1[1,1,0])   # 7 가져오기

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
4
7


In [15]:
arr_2 = np.array([[1,2],       # 2*3 형태 (2차원 배열)
                  [3,4],
                  [5,6]])

print(arr_2[[0]])              # 0행 가져와 2차원 배열(대괄호 두개로 가져옴) 만들기   # print(arr_2[[0], :])
print(arr_2[[0,2]])            # 0,2행 가져와 2차원 배열 만들기
print(arr_2[[0,1,2],[0,1,0]])  # 
print(arr_2[[0,0],[1,1]])      # 같은 위치 데이터 여러번 사용 가능

[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [16]:
arr_3 = np.array([[1,2,3],       # 4*3 형태 (2차원 배열)
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])

# 두개의 1차원 배열 생성
b = np.array([0,1,2,3])
c = np.array([0,2,0,1])         # row,col / b[],c[] / 0,0 / 1,2 / 2,0 / 3,1

print(arr_3[b,c])

[ 1  6  7 11]


### 배열 인덱싱(Boolean 인덱싱)

In [20]:
# 기본 데이터
arr = np.array([1,2,3,4,5])
 
print(arr[[True, False, True, True, False]])   # True, False
print(arr[arr >= 3])    # 조건

[1 3 4]
[3 4 5]


### 연습
* 2*6 형태의 2차원 배열 생성 후 각각 0행과 1행에서 90 이상인 숫자를 추출하라

In [25]:
score = np.array([[78,91,84,89,93,65],
                  [82,87,96,79,91,73]])

print(score[0][score[0] >= 90])
print(score[1][score[1] >= 90])

[91 93]
[96 91]
