### 배열 슬라이싱

In [2]:
import numpy as np

In [7]:
matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20]])

print(matrix[:,0])    # 0열 전체 슬라이싱
print(matrix[:,:1])   # 0열 전체 슬라이싱(2차원 유지)   # 또는 print(matrix[:,[0]])

[ 1  6 11 16]
[[ 1]
 [ 6]
 [11]
 [16]]
[[ 1]
 [ 6]
 [11]
 [16]]


In [10]:
print(matrix[1,:])    # 1행 전체 슬라이싱
print(matrix[1])      # rank > row > col 순으로 :(콜론) 생략 가능
print(matrix[1:2,:])  # 1행 전체 슬라이싱(2차원 유지)  # 또는 print(matrix[[1]])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]


In [11]:
print(matrix[:,3:])    # 3~4열 전체 슬라이싱
print(matrix[0,1:-1])  # 0행, 1~3열 슬라이싱  # 또는 print(matrix[0,1:4])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[2 3 4]


In [12]:
print(matrix[-2:,-3:])   # 2~3행, 2~4열 슬라이싱
print(matrix[1:-1,2:3])  # 1~2행, 1~2열 슬라이싱

[[13 14 15]
 [18 19 20]]
[[ 8]
 [13]]


### 배열 인덱싱, 슬라이싱 복합

In [15]:
matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20]])

print(matrix[[1,3],2:])   # 1,3행, 2~4열 슬라이싱
print(matrix[1:-1,[1,3]])  # 1~2행, 1,3열 슬라이싱

[[ 8  9 10]
 [18 19 20]]
[[ 7  9]
 [12 14]]


#### 연습문제

In [17]:
tensor = np.array([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]]])

In [20]:
# [10  2  6] 배열 추출
print(tensor[[1,0,0],[1,0,1],[0,1,2]])      # [[rank1, rank2 ...], [row1, row2 ...], [col1, col2 ...]]

[10  2  6]


In [37]:
# [[1  2]
#  [4  5]]  배열과 
print(tensor[0,:,:2])

[[1 2]
 [4 5]]


In [40]:
# [9  12] 배열 추출
print(tensor[[1,1],[0,1],[2,2]])   # 1차원(인덱싱으로 pick해서 가져오기)
print(tensor[1,:,2])               # 1차원 유지

print(tensor[1,:,2:])              # 2차원 유지(슬라이싱 활용)

[ 9 12]
[ 9 12]
[[ 9]
 [12]]
