### Reshape
* 배열의 shape 변형 함수
* 배열 요소 개수를 유지하며 형태만 변경
* 주의! 변형 전 size와 변형 후 size가 동일해야 함(이때 사이즈는 데이터 사이즈)  


* array.reshape(변환할 size)

In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],
              [4,5,6]])   # 2*3 형태 배열

arr.reshape(3,2)   # 3*2 형태로 변환

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(arr.reshape(1,6))
print(arr.reshape(6,1))

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [10]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1.shape)       # 1차원 배열 형태 확인

print(arr.reshape(6,))   # 2차원 배열의 1차원 변환도 가능

(6,)
[1 2 3 4 5 6]


In [5]:
print(arr.reshape(3,1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [6]:
print(arr.reshape(-1,2))   # 2열 지정 후 알맞게 행 자동 지정( -1 활용)

[[1 2]
 [3 4]
 [5 6]]


#### 연습문제
* range() 함수를 사용하여 1부터 36까지의 배열 생성

In [47]:
tensor = np.array(range(1,37))
tensor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

* 3x3x4 형태의 3차원 배열로 변형

In [48]:
print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [14]:
# 위에서 생성한 배열을 2차원 배열로 변형(이때 열의 개수는 9개로 지정)
print(tensor.reshape(-1,9))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


### Flatten
* 다차원 배열을 1차원 배열로 변형

In [21]:
arr=np.array([[1,2,3],
              [4,5,6]])   # 2*3 형태 배열
print(arr)

print(arr.flatten())      # shape(2,3) -> shape(6,)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [25]:
tensor = np.array(range(1,37))
print(tensor.reshape(3,3,4))

print(tensor.reshape(3,3,4).flatten())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


### Arange(range 유사)
* 값의 범위를 지정하여 채워져 있는 배열 생성
* 특정 규칙에 따라 증가하는 값을 넣을 수 있음  


* np.arange(size)
* 간격 지정 : np.arrange(star, end, step)

In [27]:
print(np.arange(30))   # np.array(range(30))과 동일

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [32]:
# 간격 지정 : np.arrange(star, end, step)
print(np.arange(0,10,2))
print(np.arange(0,2,0.2))
print(np.arange(-2,2,0.5))
print(np.arange(10,0,-1))

[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5]
[10  9  8  7  6  5  4  3  2  1]


### Arange + Reshape
* 배열 요소를 순서대로 가지는 다차원 배열 생성 가능  
* 주의! 변형 전 size와 변형 후 size가 동일해야 함(이때 사이즈는 데이터 사이즈)  

In [33]:
print(np.arange(1,26).reshape(5,5))   # 1~25의 숫자로 배열 생성 후 5*5 배열로 변형

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [34]:
print(np.arange(0,6,0.2).reshape(3,2,5))

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


#### 연습문제
* 100~190의 숫자가 10 간격으로 나열된 배열 생성 후 (2,5) 형태의 2차원 배열로 변형

In [46]:
print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


* -2부터 2까지의 숫자가 0.5 간격으로 나열된 배열 생성 후 3차원 배열로 변형(형태는 자유롭게 지정)

In [50]:
print(np.arange(-2,2.5,0.5))                    # size 확인
print(np.arange(-2,2.5,0.5).reshape(1,3,3))

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


### Zeros
* 0으로 채워진 배열 생성
* shape 지정 가능  


* np.zeros(shape, dtype)

In [52]:
print(np.zeros(shape=(5,), dtype=np.int8))
print(np.zeros((5,), int))

[0 0 0 0 0]
[0 0 0 0 0]


In [59]:
print(np.zeros((2,3)))        # dtype 생략하면 기본 자료형 float으로 생성
print(np.zeros((2,3)).dtype)  # dtype 확인

[[0. 0. 0.]
 [0. 0. 0.]]
float64


### Ones
* 1로 채워진 배열 생성
* shape 지정 가능  


* np.ones(shape, dtype)

In [60]:
print(np.ones(shape=(5,), dtype=np.int8))
print(np.ones((5,), int))

[1 1 1 1 1]
[1 1 1 1 1]


In [61]:
print(np.ones((2,3)))        # dtype 생략하면 기본 자료형 float으로 생성
print(np.ones((2,3)).dtype)  # dtype 확인

[[1. 1. 1.]
 [1. 1. 1.]]
float64


#### Empty
* shape만 주어지고 비어있는 배열 생성
* 배열만 생성하고 값을 주지 않아 메모리에 저장되어 있던 기존 값이 저장될 수 있음  


* np.empty(shape, dtype)

In [66]:
print(np.empty(shape=(10,), dtype=np.int32))     # 메모리에 값이 없으면 0으로 채워지나 값이 있으면 메모리의 값으로 생성
print(np.empty((2,5), np.int8))

[100 110 120 130 140 150 160 170 180 190]
[[1 1 1 1 0]
 [1 1 1 1 1]]


In [67]:
print(np.empty((2,5), np.int8))   # dtype 생략하면 기본 자료형 float으로 생성
print(np.zeros((2,5)).dtype)      # dtype 확인

[[1 1 1 1 0]
 [1 1 1 1 1]]
float64


#### Zeros_like / Ones_like / Empty_like
* 입력 받은 배열과 같은 shape, dtype의 배열 생성

In [92]:
matrix = np.arange(24).reshape(4,6)
print(matrix, '\n')
print(np.zeros_like(matrix))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [91]:
matrix = np.arange(-2,2,0.2).reshape(2,10)
print(matrix, '\n')
print(np.ones_like(matrix))

[[-2.0000000e+00 -1.8000000e+00 -1.6000000e+00 -1.4000000e+00
  -1.2000000e+00 -1.0000000e+00 -8.0000000e-01 -6.0000000e-01
  -4.0000000e-01 -2.0000000e-01]
 [-4.4408921e-16  2.0000000e-01  4.0000000e-01  6.0000000e-01
   8.0000000e-01  1.0000000e+00  1.2000000e+00  1.4000000e+00
   1.6000000e+00  1.8000000e+00]] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [90]:
matrix = np.arange(25).reshape(5,5)
print(matrix, '\n')
print(np.empty_like(matrix))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Identity
* 단위행렬 : 주 대각선 값이 1이고 나머지는 0인 정사각 행렬  


* np.identity(size, dtype)

In [76]:
print(np.identity(5, dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [74]:
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


### Eye
* 대각선이 1로 채워지는 행렬이나 대각선 시작 위치 지정 가능


* np.eye(size, M, k, dtype)
* M : 보여지는 열의 개수를 지정(정사각형뿐만 아니라 직사각형 가능)
* k : 대각선 시작 위치(입력 받은 수 만큼 오른쪽으로 이동)

In [78]:
print(np.eye(5, dtype=np.int8))   # M, k 생략시 단위행렬과 흡사

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [84]:
print(np.eye(5, k=2),'\n')
print(np.eye(5, k=-1))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [89]:
print(np.eye(5, M=10, k=4, dtype=np.int8), '\n')
print(np.eye(5, M=10, k=-2, dtype=np.int8))

[[0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]] 

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]]


### Full
* 입력 값으로 채워지는 행렬


* np.full((shape), value)

In [96]:
print(np.full((2,5), 3), '\n')   # 3으로 채워진 (2,5)행렬
print(np.full((5,4), 'a'))   # a로 채워진 (5,4)행렬

[[3 3 3 3 3]
 [3 3 3 3 3]] 

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


### Random.randit
* 주어진 범위 안의 랜덤한 값을 뽑는 함수


* np.random.randit(range)

In [100]:
print(np.random.randint(6))      # 0~5까지의 정수 중 하나 뽑기
print(np.random.randint(1,20))   # 1~19까지의 정수 중 하나 뽑기
print(np.random.randint(1,20,2)) # 여기서 2는 간격이 아니라 뽑는 개수임

1
16
[6 5]


### Random.rand(양수)
* 랜덤한 값으로 채워지는 배열
* 0~1 사이의 값을 가짐(표준정규분포 난수를 shape 형태의 배열로 생성)


* np.random.rand(shape)

In [104]:
print(np.random.rand(3,), '\n')   # 입력한 형태를 가진 랜덤(0~1) 배열 생성
print(np.random.rand(3,2))

[0.82671889 0.96507056 0.02334286] 

[[0.30366552 0.20884861]
 [0.37204437 0.09502743]
 [0.28333237 0.3750967 ]]


### Random.randn(음수, 양수)
* 랜덤한 값으로 채워지는 배열
* 평균 0, 표준편차 1의 가우시안 표준정규분포 난수를 shape 형태의 배열로 생성


* np.random.randn(shape)

In [112]:
print(np.random.randn(3,), '\n') 
print(np.random.randn(3,2))

[-0.39532735 -1.08399887  0.65938915] 

[[-1.71618966  0.67141739]
 [ 0.59537935 -1.74357435]
 [-1.31979644  0.27574128]]
