### Sum(합)
* ndarray.sum()

In [1]:
import numpy as np

In [2]:
matrix = np.arange(1,7).reshape(2,3)
print(matrix, '\n')

print(matrix.sum())

[[1 2 3]
 [4 5 6]] 

21


In [4]:
# ndarray.sum(axis = 0 또는 1)
print(matrix, '\n')

print(matrix.sum(axis=0))   # 행끼리 더하기(위 아래)
print(matrix.sum(axis=1))   # 열끼리 더하기(좌 우)

[[1 2 3]
 [4 5 6]] 

[5 7 9]
[ 6 15]


In [7]:
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor,'\n')

print(tensor.sum(),'\n')        # 3차원 배열 합
print(tensor.sum(axis=0),'\n')  # 차원끼리 더하기
print(tensor.sum(axis=1),'\n')  # 행끼리 더하기(위 아래)
print(tensor.sum(axis=2),'\n')  # 열끼리 더하기(좌 우)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]] 

171 

[[21 24 27]
 [30 33 36]] 

[[ 5  7  9]
 [17 19 21]
 [29 31 33]] 

[[ 6 15]
 [24 33]
 [42 51]] 



In [12]:
# sum()과 배열함수 sum()
print(tensor.sum(axis=0))
print(np.sum(tensor, axis=0))

[[21 24 27]
 [30 33 36]]
[[21 24 27]
 [30 33 36]]


### Mean(평균)
* ndarray.mean()

In [8]:
matrix = np.arange(1,7).reshape(2,3)
print(matrix, '\n')

print(matrix.mean())

[[1 2 3]
 [4 5 6]] 

3.5


In [9]:
print(matrix, '\n')

print(matrix.mean(axis=0))   # 행끼리 평균(위 아래)
print(matrix.mean(axis=1))   # 열끼리 평균(좌 우)

[[1 2 3]
 [4 5 6]] 

[2.5 3.5 4.5]
[2. 5.]


In [10]:
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor,'\n')

print(tensor.mean(),'\n')        # 3차원 배열 합
print(tensor.mean(axis=0),'\n')  # 차원끼리 평균
print(tensor.mean(axis=1),'\n')  # 행끼리 평균(위 아래)
print(tensor.mean(axis=2),'\n')  # 열끼리 평균(좌 우)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]] 

9.5 

[[ 7.  8.  9.]
 [10. 11. 12.]] 

[[ 2.5  3.5  4.5]
 [ 8.5  9.5 10.5]
 [14.5 15.5 16.5]] 

[[ 2.  5.]
 [ 8. 11.]
 [14. 17.]] 



### Std(표준편차)
* ndarray.std()

In [13]:
matrix = np.arange(1,7).reshape(2,3)
print(matrix, '\n')

print(matrix.std())

[[1 2 3]
 [4 5 6]] 

1.707825127659933


In [14]:
print(matrix, '\n')

print(matrix.std(axis=0))   # 행끼리 표준편차(위 아래)
print(matrix.std(axis=1))   # 열끼리 표준편차(좌 우)

[[1 2 3]
 [4 5 6]] 

[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [15]:
# 3차원의 경우 위와 동일

* Exp(지수) : ndarray.exp(array)
* Log(로그) : ndarray.log(array)
* Sqrt(제곱근) : ndarray.sqrt(array)

### Sort(정렬)
* 1차원

In [18]:
# randint을 사용하여 1~100 숫자 중 5개를 뽑아 배열 생성(1차원)
vector = np.array([np.random.randint(1,100) 
                   for n in range(5)])       # 아래 참고!! 확인

print(vector)

[ 3 52 63 60 50]


In [19]:
print(np.sort(vector))        # 오름차순 정렬
print(np.sort(vector)[::-1])  # 내림차순 정렬

[ 3 50 52 60 63]
[63 60 52 50  3]


#### 참고!! list 내 for문

In [26]:
# 리스트 안의 for문
[i for i in range(5)]  # 리스트 안에 i를 넣으려고 하는데 for문에 해당하는 값을 넣음

[0, 1, 2, 3, 4]

In [21]:
a=[]
for i in range(5) :
    a.append(i)
print(a)

[0, 1, 2, 3, 4]


In [23]:
x=3
[x for i in range(5) if x==i]

[3]

In [24]:
list_=[1,2,3,4,5,6,7,8,9,10]
list2_=[num * 3                # 리스트에 넣고자 하는 값
        for num in list_       # 
        if num % 2 == 1]       # if 조건에 만족하면 for문

print(list2_)

[3, 9, 15, 21, 27]


* 2차원

In [27]:
# randint을 사용하여 1~100 숫자 중 5개를 뽑아 배열 생성(2차원)
matrix = np.array([np.random.randint(1,100) 
                   for n in range(20)]).reshape(4,5)

print(matrix)

[[88 27 55 15 57]
 [38 30 90 56 52]
 [26 64 48 52 69]
 [81 54 97  8 22]]


In [30]:
print(np.sort(matrix))          # 오름차순(열기준) 정렬
print(np.sort(matrix, axis=0))  # 내림차순(행기준) 정렬

[[15 27 55 57 88]
 [30 38 52 56 90]
 [26 48 52 64 69]
 [ 8 22 54 81 97]]
[[26 27 48  8 22]
 [38 30 55 15 52]
 [81 54 90 52 57]
 [88 64 97 56 69]]


### Vstack(배열 합치기)
* 2개 이상 배열을 수직으로 합체


* np.vstack([arr1, arr2])

In [31]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.vstack([vector1, vector2]))

[[1 2 3]
 [4 5 6]]


### Hstack(배열 합치기)
* 2개 이상 배열을 수평으로 합체


* np.hstack([arr1, arr2])

In [33]:
# 1차원
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.hstack([vector1, vector2]))

[1 2 3 4 5 6]


In [32]:
# 2차원
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.hstack([vector1, vector2]))

[[1 4]
 [2 5]
 [3 6]]


### Concatenate(배열 합치기)
* 2개 이상의 배열을 수직, 수평으로 합체


* np.concatenate(arr1, arr2, axis)

In [41]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.concatenate([vector1, vector2], axis=0))   # 1차원 벡터는 축이 1개임

[1 2 3 4 5 6]


In [47]:
matrix1 = np.array([[1,2,3]])
matrix2 = np.array([[4,5,6]])

print(np.concatenate([matrix1, matrix2], axis=0))
print(np.concatenate([matrix1, matrix2], axis=1))   # 2차원

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [45]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.concatenate([vector1, vector2], axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [57]:
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)
print(matrix1)
print(vector2,'\n')

# print(np.concatenate([matrix1, vector2], axis=0))  # 에러
print(np.concatenate([matrix1, vector2], axis=1))

[[1 2]
 [3 1]
 [2 3]]
[[4]
 [5]
 [6]] 

[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [56]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(matrix1)
print(matrix2,'\n')

print(np.concatenate([matrix1, matrix2], axis=0))
print(np.concatenate([matrix1, matrix2], axis=1))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Transpose(행, 열 바꾸기)
* ndarray.transpose()
* ndarray.T

In [63]:
matrix3=np.array([[5,6]])
print(matrix3, '\n')

print(matrix3.transpose())
print(matrix3.T)

print('\n', matrix3.shape, matrix3.transpose().shape)   # 행, 열 변환 확인

[[5 6]] 

[[5]
 [6]]
[[5]
 [6]]

 (1, 2) (2, 1)


### Transpose + Concatenate
* 형태를 바꿔 서로 결합할 수 없는 배열을 합침

### 인덱스 반환 함수
* 최대값, 최소값의 인덱스

In [66]:
a = np.arange(1,11).reshape(2,5)
print(a)

print(np.argmax(a), np.argmin(a))
print(np.argmax(a, axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9 0
[1 1 1 1 1]


### Fancy index (배열 인덱싱)
* 인덱싱 값을 가지는 배열로 인덱싱

#### 인덱스 반환 함수 + Fancy index

In [69]:
a=np.arange(10,20)
b=np.argmax(a)
print(a)
print(b)

print(a[b])

[10 11 12 13 14 15 16 17 18 19]
9
19
