In [1]:
import numpy as np

### 산술연산

In [2]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


In [14]:
# shape이 같은 배열 연산 가능
arr1 = np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2 = np.arange(11,17,dtype=np.float32).reshape(2,3)

print(arr1+arr2,'\n')
print(arr1-arr2,'\n')
print(arr1*arr2,'\n')
print(arr1/arr2,'\n')
print(arr1**arr2,'\n')    # 제곱
print(arr1//arr2,'\n')    # 몫
print(arr1%arr2)     # 나머지

[[12. 14. 16.]
 [18. 20. 22.]] 

[[-10. -10. -10.]
 [-10. -10. -10.]] 

[[11. 24. 39.]
 [56. 75. 96.]] 

[[0.09090909 0.16666667 0.23076923]
 [0.2857143  0.33333334 0.375     ]] 

[[1.0000000e+00 4.0960000e+03 1.5943230e+06]
 [2.6843546e+08 3.0517578e+10 2.8211098e+12]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [4. 5. 6.]]


### Numpy 연산함수
* np.add()       : +
* np.subtract()  : -
* np.multiply()  : *
* np.devide()    : /

In [13]:
print(np.add(arr1,arr2),'\n')
print(np.subtract(arr1,arr2),'\n')
print(np.multiply(arr1,arr2),'\n')
print(np.divide(arr1,arr2))

[[12. 14. 16.]
 [18. 20. 22.]] 

[[-10. -10. -10.]
 [-10. -10. -10.]] 

[[11. 24. 39.]
 [56. 75. 96.]] 

[[0.09090909 0.16666667 0.23076923]
 [0.2857143  0.33333334 0.375     ]]


### Broadcasting
* 연산하고자 하는 배열의 모양이 다른 경우 연산이 가능하도록 지원
* but! 행과 열 중 하나의 모양은 동일해야 함 > 자동 적용

In [ ]:
# 일반적으로 에러 발생
# arr3=np.arange(10).reshape(5,2)
# arr4=np.arange(10).reshape(2,5)
# print(arr3+arr4)

* 스칼라와 배열의 연산

In [16]:
# 스칼라에서는 어느 차원이든 브로드캐스팅 지원
scalar = 10
vector = np.array([1,2,3])
print(scalar + vector)      # -,*,/ 등 모두 적용 가능

[11 12 13]


In [17]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar + matrix)

[[11 12 13]
 [14 15 16]]


In [20]:
scalar = 10
tensor = np.arange(1,19).reshape(3,2,3)
print(scalar + tensor)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]]


* 백터와 백터의 브로드캐스팅 연산

In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1,'\n')
print(arr2)

[1 2 3] 

[[1]
 [2]
 [3]]


In [27]:
print(arr1 + arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


* 백터와 매트릭스의 연산

In [23]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix + vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [24]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(3,1)
print(matrix + vector)

[[12 13 14]
 [16 17 18]
 [20 21 22]]


### 행렬 연산
* np.dot(arr1,arr2)

In [29]:
# 일반적인 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1*arr2)

[1 4 9]


In [31]:
# n.dot 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T

print(np.dot(arr1,arr2))
print(arr1.dot(arr2))
print(arr1@arr2)

14
14
14


In [32]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
