In [17]:
import numpy as np

### 파일 처리

In [7]:
# 파일 저장(tofile)
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[ 1.06280276 -0.45325563 -1.75642458  0.87793083  1.27385786]
 [-1.21064817  1.98653335  0.06695576 -0.10245002 -0.59917824]
 [ 0.59926986  0.8224285  -0.72056861 -0.03360266 -0.9725805 ]]


In [10]:
# 파일 불러오기(fromfile)
m = np.fromfile('C:\STUDY\StudyPython_kim\day2/n.npy')
print(m)

[ 1.06280276 -0.45325563 -1.75642458  0.87793083  1.27385786 -1.21064817
  1.98653335  0.06695576 -0.10245002 -0.59917824  0.59926986  0.8224285
 -0.72056861 -0.03360266 -0.9725805 ]


In [13]:
# 파일 저장, 불러오기(np.save, np.load)
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[ 1.06280276 -0.45325563 -1.75642458  0.87793083  1.27385786]
 [-1.21064817  1.98653335  0.06695576 -0.10245002 -0.59917824]
 [ 0.59926986  0.8224285  -0.72056861 -0.03360266 -0.9725805 ]]


### txt 파일 저장

In [3]:
# 파일 저장(np.savetxt)
n = np.random.randn(3,5)
print(n)
np.savetxt('n.txt', n)

[[-0.27798348 -1.15318376 -0.93995203  0.42070307  0.87951165]
 [-1.18678296 -0.53694242  0.32699627  1.09722822  0.90473471]
 [ 0.40067516  0.18209757  0.52434749  1.42181706 -0.55137886]]


In [9]:
# 파일 불러오기(np.loadtxt)
np.loadtxt('C:\STUDY\StudyPython_kim\day2/n.txt')

array([[-0.27798348, -1.15318376, -0.93995203,  0.42070307,  0.87951165],
       [-1.18678296, -0.53694242,  0.32699627,  1.09722822,  0.90473471],
       [ 0.40067516,  0.18209757,  0.52434749,  1.42181706, -0.55137886]])

### csv 파일 저장

In [12]:
# 파일 저장(np.savetxt)
n = np.random.randn(3,5)
print(n)
np.savetxt('n.csv', n, delimiter = ',')      # txt와 동일하며 확장자만 변경, 구분자 지정

[[-0.54927464 -1.18530586  1.30821208  1.86201368  1.51504916]
 [ 0.46099531  0.08413438  1.38231432 -0.17162843 -0.29518279]
 [ 0.05991439 -0.29790772  0.24439864 -0.75382072 -0.63258858]]


In [14]:
# 파일 불러오기(np.loadtxt)
np.loadtxt('C:\STUDY\StudyPython_kim\day2/n.csv', delimiter = ',')

array([[-0.54927464, -1.18530586,  1.30821208,  1.86201368,  1.51504916],
       [ 0.46099531,  0.08413438,  1.38231432, -0.17162843, -0.29518279],
       [ 0.05991439, -0.29790772,  0.24439864, -0.75382072, -0.63258858]])

#### 연습문제
* 1~25 범위의 (5,5) 2차원 행렬을 생성하고 구분자를 ,로 지정해서 data.csv에 저장

In [37]:
a = np.arange(1,26).reshape(5,5)
np.savetxt('C:\STUDY\StudyPython_kim\day2/data.csv', a, delimiter=',')
np.loadtxt('C:\STUDY\StudyPython_kim\day2/data.csv', delimiter = ',', dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

* 06_data1.txt 파일을 읽어와서 dtype=str로 변수 arr1에 저장하고 출력

In [40]:
arr1 = np.loadtxt('C:\STUDY\StudyPython_kim\day2/06_data1.txt', dtype=str)   # 또는 np.str_
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [41]:
arr1_ = np.loadtxt('C:\STUDY\StudyPython_kim\day2/06_data1.txt', delimiter= '\t', dtype=str)  # \t :탭
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


* 06_data2.txt 파일을 읽어와서 변수 arr2에 저장하고 출력

In [42]:
arr2 = np.loadtxt('C:\STUDY\StudyPython_kim\day2/06_data2.txt', delimiter=',', dtype = np.int8)
print(arr2)

[[ 1 15 14  4]
 [12  6  7  9]
 [ 8 10 11  5]
 [13  3  2 16]]
