### 예제 1

In [2]:
import numpy as np

* 01) 파일 읽어오기

In [9]:
data = np.loadtxt('C:\STUDY\StudyPython_kim/day3/ex1_지역별전기요금.csv', delimiter = ',', dtype = int)

In [7]:
print(data)

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]
 [      6  668623     364   35245]
 [      7  425659     344   32331]
 [      8  947300     366   36274]
 [      9 2737725     361   36569]
 [     10   49394     580   57091]
 [     11  323151     353   35470]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [     14  634696     285   28556]
 [     15  258605     221   22180]
 [     16  742285     282   27901]
 [     17  584500     268   26899]]


In [10]:
print(data[:5,:])   # 상위 5개 데이터 출력

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


* 02) 데이터 확인

In [11]:
print(data.shape)             # 데이터 모양 확인
print(np.unique(data[:,0]))   # 중복 지역 확인

(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [14]:
print(np.sort(data[:, 1]))    # 가구수 정렬

[  49394  258605  323151  380425  425659  565082  584500  634696  668623
  726699  734723  742285  947300 1131034 1144913 2737725 2827233]


In [12]:
# arg 함수는 정렬된 인덱스 추출
# 데이터의 크기순으로 정렬(argsort)
print(data[:,1].argsort())

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]


In [16]:
print(data[ data[:,1].argsort()[::-1] ])  

[[      2 2827233     444   45111]
 [      9 2737725     361   36569]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      8  947300     366   36274]
 [     16  742285     282   27901]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [      6  668623     364   35245]
 [     14  634696     285   28556]
 [     17  584500     268   26899]
 [      1  565082     273   27177]
 [      7  425659     344   32331]
 [      5  380425     391   38020]
 [     11  323151     353   35470]
 [     15  258605     221   22180]
 [     10   49394     580   57091]]


* 03_데이터 통계

In [18]:
print(np.sum(data[:,1]))            # 전국 대상 가구수의 합
print(round(data[:,2].mean(), 2))   # 가구당 평균 전력 사용량의 전국 평균값

14882047
335.18


In [21]:
# 전국 대상 가구수의 합
print(data[:,1])
data[:,1].sum()   # 또는 np.sum(data[:,1])

[ 565082 2827233 1144913 1131034  380425  668623  425659  947300 2737725
   49394  323151  734723  726699  634696  258605  742285  584500]


14882047

In [23]:
# 가구당 평균 전력 사용량의 전국 평균값
print(data[:,2])
data[:,2].mean()  # 또는 np.mean(data[:,2])   # round(data, 2) : 소수점 2자리까지

[273 444 289 230 391 364 344 366 361 580 353 398 249 285 221 282 268]


335.1764705882353

In [25]:
# 무식하게 평균 구하기
e_sum = np.sum(data[:,2])
print(e_sum)

n_rows = data.shape[0]
print(n_rows)

print('가구당 평균 전력 사용량의 전국 평균값 : ', e_sum/n_rows)

5698
17
가구당 평균 전력 사용량의 전국 평균값 :  335.1764705882353


In [26]:
# 가구당 평균 전력 사용량이 전국 평균(avg_) 이상인 지역과 대상 가구수 추출
avg_ = data[:,2].mean()
print(data[data[:,2] > avg_, 0:2])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


In [28]:
data[:,2] > avg_   # 위 조건 확인

array([False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False])