### 예제 2

In [1]:
import numpy as np

In [39]:
data2 = np.loadtxt('C:\STUDY\StudyPython_kim/day3/ex2_전년대비_시도별_교통사망사고.csv', delimiter = ',', dtype = float)
print(data2)
# 발생년도, 구분, 발생건수, 구성비(%), 증감수, 증감률

[[ 2.014e+03  1.000e+00  2.180e+02  4.800e+00 -9.000e+00 -4.000e+00]
 [ 2.014e+03  2.000e+00  8.720e+02  1.900e+01 -4.500e+01 -4.900e+00]
 [ 2.014e+03  3.000e+00  4.010e+02  8.700e+00 -4.500e+01 -1.010e+01]
 [ 2.014e+03  4.000e+00  4.640e+02  1.010e+01 -4.100e+01 -8.100e+00]
 [ 2.014e+03  5.000e+00  9.900e+01  2.200e+00 -5.000e+00 -4.800e+00]
 [ 2.014e+03  6.000e+00  1.820e+02  4.000e+00  1.900e+01  1.170e+01]
 [ 2.014e+03  7.000e+00  9.900e+01  2.200e+00  8.000e+00  8.800e+00]
 [ 2.014e+03  8.000e+00  1.630e+02  3.600e+00 -4.700e+01 -2.240e+01]
 [ 2.014e+03  9.000e+00  3.860e+02  8.400e+00  1.400e+01  3.800e+00]
 [ 2.014e+03  1.000e+01  2.000e+01  4.000e-01  0.000e+00  0.000e+00]
 [ 2.014e+03  1.100e+01  1.030e+02  2.200e+00 -1.600e+01 -1.340e+01]
 [ 2.014e+03  1.200e+01  1.440e+02  3.100e+00 -6.000e+00 -4.000e+00]
 [ 2.014e+03  1.300e+01  4.000e+02  8.700e+00 -3.500e+01 -8.000e+00]
 [ 2.014e+03  1.400e+01  3.170e+02  6.900e+00 -3.500e+01 -9.900e+00]
 [ 2.014e+03  1.500e+01  8.600e+01

* [문제1] 위 파일을 읽어보고 상위 3개의 (발생년도, 발생건수, 구성비)의 데이터를 추출해 봅시다.

In [40]:
print(data2[:3,(0,2,3)])   # (0,2,3) 또는 [0,2,3] 둘 다 가능

[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


* [문제2] 위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출해 봅시다.

In [41]:
# 8 : 부산
print(data2[7,:])

[2014.     8.   163.     3.6  -47.   -22.4]


In [48]:
print(data2[data2[:,1] == 8])

[[2014.     8.   163.     3.6  -47.   -22.4]]


* [문제3] 위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산해 봅시다.

In [42]:
print('전국 사고 발생건수 합계 : ', np.sum(data2[:,2]))
print('전국 사고 발생건수 평균 : ', round(np.mean(data2[:,2]),2))

전국 사고 발생건수 합계 :  4583.0
전국 사고 발생건수 평균 :  269.59


* [문제4] 위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [43]:
print(data2[np.argmax(data2[:,4]),:])

[2014.     6.   182.     4.    19.    11.7]


In [50]:
print(data2[data2[:,4] == max(data2[:,4])])

[[2014.     6.   182.     4.    19.    11.7]]


* [문제5] 위 데이터에서 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출해 봅시다.

In [44]:
print(data2[np.argmin(data2[:,5]),:])

[2014.     8.   163.     3.6  -47.   -22.4]


In [51]:
print(data2[data2[:,5] == min(data2[:,5])])

[[2014.     8.   163.     3.6  -47.   -22.4]]


* [문제6] 위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출해 봅시다.

In [45]:
print(data2[data2[:,2] >= 400,:][:,(1,2,4,5)])

[[  2.  872.  -45.   -4.9]
 [  3.  401.  -45.  -10.1]
 [  4.  464.  -41.   -8.1]
 [ 13.  400.  -35.   -8. ]]
